name: PlayerTP
author: _True_Religion
version: 1.1
main: xyz.trrlgn.teleporttoplayer.PlayerTP
description: Simple teleport plugin to allow players to teleport to others
api-version: 1.13
commands:
  teleport:
    usage: /teleport
    aliases: [tp]